--PROJETO DE SQL 
--IAGO LOURENÇO 15610116

--CRIACAO DAS TABELAS REQUERIDAS
CREATE TABLE ALUNOS (RA NUMBER,NOME VARCHAR2(20),DATA_NASC DATE,NUM_CURSO NUMBER);

CREATE TABLE ALUNOS_GRAD (CD NUMBER,RA NUMBER);
CREATE TABLE ALUNOS_POS (ORIENTADOR VARCHAR2(20),RA NUMBER);

CREATE TABLE CURSAM (RA NUMBER,COD_DISC NUMBER,FREQ NUMBER);
CREATE TABLE CURSARAM (RA NUMBER,COD_DISC NUMBER,SEMESTRE NUMBER,NOTA NUMBER,FREQ NUMBER,STATUS CHAR);

CREATE TABLE DISCIPLINAS (COD NUMBER,NOME VARCHAR2(30),CRED NUMBER);

CREATE TABLE PRE_REQ (COD_DISC NUMBER,COD_PRE_REQ NUMBER);

CREATE TABLE GRADE (COD_DISC NUMBER,NUM_CURSO NUMBER);

CREATE TABLE CURSOS (NUM NUMBER,NOME VARCHAR2(20));

--DEFINICAO DAS CONSTRAINTS NECESSARIAS

ALTER TABLE ALUNOS ADD CONSTRAINT PK_ALUNOS PRIMARY KEY(RA);
ALTER TABLE ALUNOS_GRAD ADD CONSTRAINT PK_ALUNOS_GRAD PRIMARY KEY  (RA);
ALTER TABLE ALUNOS_POS ADD CONSTRAINT PK_ALUNOS_POS PRIMARY KEY (RA); 
ALTER TABLE DISCIPLINAS ADD CONSTRAINT PK_DISCIPLINAS PRIMARY KEY (COD);
ALTER TABLE CURSOS ADD CONSTRAINT PK_CURSOS PRIMARY KEY (COD_DISC);

ALTER TABLE ALUNOS ADD CONSTRAINT FK_ALUNOS FOREIGN KEY (NUM_CURSO) REFERENCES CURSOS;
ALTER TABLE ALUNOS_GRAD ADD CONSTRAINT FK_ALUNOS_GRAD FOREIGN KEY (RA) REFERENCES ALUNOS;
ALTER TABLE ALUNOS_POS ADD CONSTRAINT FK_ALUNOS_POS FOREIGN KEY (RA) REFERENCES ALUNOS; 
--ALTER TABLE CURSAM ADD CONSTRAINT PK_CURSAM_RA PRIMARY KEY (RA);
--ALTER TABLE CURSAM ADD CONSTRAINT PK_CURSAM_COD_DISC PRIMARY KEY (COD_DISC);

ALTER TABLE CURSAM ADD CONSTRAINT FK_CURSAM_RA FOREIGN KEY (RA) REFERENCES ALUNOS;
ALTER TABLE CURSAM ADD CONSTRAINT FK_CURSAM_COD_DISC FOREIGN KEY (COD_DISC) REFERENCES DISCIPLINAS;
--ALTER TABLE CURSARAM ADD CONSTRAINT PK_CURSARAM_RA PRIMARY KEY (RA);
--ALTER TABLE CURSARAM ADD CONSTRAINT PK_CURSARAM_COD_DISC PRIMARY KEY (COD_DISC);
ALTER TABLE CURSARAM ADD CONSTRAINT FK_CURSARAM_RA FOREIGN KEY (RA) REFERENCES ALUNOS;
ALTER TABLE CURSARAM ADD CONSTRAINT FK_CURSARAM_COD_DISC FOREIGN KEY (COD_DISC) REFERENCES DISCIPLINAS;
ALTER TABLE CURSARAM ADD CONSTRAINT CH_STATUS CHECK (STATUS IN ('A','R')); 

--ALTER TABLE PRE_REQ ADD CONSTRAINT PK_PRE_REQ PRIMARY KEY (COD_PRE_REQ);
ALTER TABLE PRE_REQ ADD CONSTRAINT FK_PRE_REQ_COD_DISC FOREIGN KEY (COD_DISC) REFERENCES DISCIPLINAS;
ALTER TABLE PRE_REQ ADD CONSTRAINT FK_PRE_REQ_COD FOREIGN KEY (COD_PRE_REQ) REFERENCES DISCIPLINAS;

ALTER TABLE GRADE ADD CONSTRAINT FK_GRADE_COD_DISC FOREIGN KEY (COD_DISC) REFERENCES DISCIPLINAS;
ALTER TABLE GRADE ADD CONSTRAINT FK_GRADE_NUM_CURSO FOREIGN KEY (NUM_CURSO) REFERENCES CURSOS;

CREATE SEQUENCE SEQ_NUM_CURSO START WITH 1;
CREATE SEQUENCE SEQ_RA START WITH 19000000;
CREATE SEQUENCE SEQ_COD_DISC START WITH 100;


--INSERTS INICIAIS
--40 alunos (30 de graduação e 10 de Pós)
--80 Disciplinas em Curso e 80 já cursadas  


INSERT INTO CURSOS VALUES(SEQ_NUM_CURSO.NEXTVAL,'ENGENHARIA DA COMPUTACAO');
INSERT INTO CURSOS VALUES(SEQ_NUM_CURSO.NEXTVAL,'HISTORIA');
INSERT INTO CURSOS VALUES(SEQ_NUM_CURSO.NEXTVAL,'FISICA');
INSERT INTO CURSOS VALUES(SEQ_NUM_CURSO.NEXTVAL,'ADMINISTRACAO');

INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'CALCULO',10);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'SISTEMAS OPERACIONAIS',5);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'ECONOMIA',3);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'DIREITO',4);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'TERMODINAMICA',4);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'PARADIGMAS',2);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'CIRCUITOS',2);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'BANCO DE DADOS',5);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'MATEMATICA FINANCEIRA',3);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'RELATIVIDADE GERAL',7);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'FISICA QUANTICA',9);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'QUIMICA',6);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'PROBABILIDADE',10);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'INTRODUCAO A PROGRAMACAO',2);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'ALGORITMOS',4);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'COMPILADORES',7);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'MECANICA',4);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'GUERRAS MUNDIAIS',5);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'ERA VARGAS',6);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'ERA COLLOR',5);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'PERIODO CREATACEO',3);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'PERIODO TRIASSICO',4);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'PERIODO JURASSICO',4);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'MICROBIOLOGIA',7);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'DIREITOS HUMANOS',3);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'CONTABILIDADE',5);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'ETICA',3);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'FISICA LABORATORIAL',7);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'INTELIGENCIA ARTIFICIAL',6);
INSERT INTO DISCIPLINAS VALUES(SEQ_COD_DISC.NEXTVAL,'ROBOTICA',7);

INSERT INTO PRE_REQ VALUES(104,100);
INSERT INTO PRE_REQ VALUES(109,100);
INSERT INTO PRE_REQ VALUES(110,100);
INSERT INTO PRE_REQ VALUES(112,100);
INSERT INTO PRE_REQ VALUES(101,114);
INSERT INTO PRE_REQ VALUES(105,114);
INSERT INTO PRE_REQ VALUES(121,120);
INSERT INTO PRE_REQ VALUES(122,120);
INSERT INTO PRE_REQ VALUES(128,100);
INSERT INTO PRE_REQ VALUES(128,114);
INSERT INTO PRE_REQ VALUES(128,126);
INSERT INTO PRE_REQ VALUES(127,110);
INSERT INTO PRE_REQ VALUES(108,125);
INSERT INTO PRE_REQ VALUES(115,101);
INSERT INTO PRE_REQ VALUES(129,116);
