--CRIACAO DAS TABELAS
CREATE TABLE FUNC (COD NUMBER, NOME VARCHAR2(15), DATA_ADM DATE, SALARIO NUMBER (10,2)); 
CREATE TABLE FUNC_BAK (COD NUMBER, NOME VARCHAR2(15), DATA_ADM DATE, SALARIO NUMBER (10,2));
CREATE TABLE LOG (ID NUMBER, CHAVE NUMBER, TIPO VARCHAR2(1), DATA DATE, STATUS VARCHAR2(1));
--DECLARACAO DE CHAVES PRIMARIAS E ESTRANGEIRAS
ALTER TABLE FUNC ADD CONSTRAINT PK_FUNC  PRIMARY KEY (COD);
ALTER TABLE FUNC_BAK ADD CONSTRAINT PK_FUNC_BAK  PRIMARY KEY (COD);
ALTER TABLE LOG  ADD CONSTRAINT PK_LOG PRIMARY KEY (ID); 



--SEQUENCE DA TABELA LOG
CREATE SEQUENCE SEQ_LOG START WITH 10;

--TRIGGER QUE POPULA A TABELA LOG
CREATE OR REPLACE TRIGGER MONITORA_FUNC AFTER INSERT OR UPDATE OR DELETE ON FUNC FOR EACH ROW
BEGIN
    IF INSERTING THEN  
       INSERT INTO LOG VALUES (SEQ_LOG.NEXTVAL, :NEW.COD, 'I',SYSDATE,'N');
    ELSIF UPDATING THEN 
       INSERT INTO LOG VALUES (SEQ_LOG.NEXTVAL, :NEW.COD, 'A',SYSDATE,'N');
    ELSE  
       INSERT INTO LOG VALUES (SEQ_LOG.NEXTVAL, :OLD.COD, 'E',SYSDATE,'N');
    END IF;
END;

--PROCEDURE QUE PROCESSA A TABELA LOG
CREATE OR REPLACE PROCEDURE PRC_FUNC  IS

TMP_COD NUMBER;
TMP_NOME VARCHAR2(15); 
TMP_DATA_ADM DATE; 
TMP_SALARIO NUMBER(10,2);

BEGIN
	FOR DADOS IN (SELECT * FROM LOG  WHERE STATUS = 'N' ORDER BY DATA) 
		LOOP

		IF DADOS.TIPO = 'I' THEN
		BEGIN
			SELECT COD,NOME,DATA_ADM,SALARIO INTO TMP_COD,TMP_NOME,TMP_DATA_ADM,TMP_SALARIO FROM FUNC WHERE COD = DADOS.CHAVE;
			INSERT INTO FUNC_BAK VALUES (TMP_COD, TMP_NOME, TMP_DATA_ADM,TMP_SALARIO); 
			EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
		END;
	
		ELSIF DADOS.TIPO = 'A' THEN
			
			SELECT COD, NOME, DATA_ADM, SALARIO INTO TMP_COD, TMP_NOME, TMP_DATA_ADM, TMP_SALARIO FROM FUNC WHERE COD=DADOS.CHAVE;
			UPDATE FUNC_BAK  SET COD = TMP_COD,NOME = TMP_NOME,DATA_ADM = TMP_DATA_ADM,SALARIO = TMP_SALARIO WHERE COD=TMP_COD;

		ELSIF DADOS.TIPO = 'E' THEN
		
			DELETE FROM FUNC_BAK  WHERE COD = DADOS.CHAVE;
		
		END IF;
			UPDATE LOG SET STATUS='S'  WHERE ID = DADOS.ID;

	END LOOP
COMMIT;
END;

INSERT INTO FUNC VALUES(100,'MARIANO',TO_DATE('10/04/2018','dd/mm/yy'),1876);
INSERT INTO FUNC VALUES(200,'JOAO',TO_DATE('20/09/2018','dd/mm/yy'),2713);
INSERT INTO FUNC VALUES(300,'PEDRO',TO_DATE('16/02/2018','dd/mm/yy'),9123);
INSERT INTO FUNC VALUES(400,'PAULO',TO_DATE('26/10/2018','dd/mm/yy'),7231);






