--
--	Aluno - Iago Jardim Lourenço
--	RA. - 1561016
--


-- CRIA TABELA SECAO
CREATE TABLE SECAO(NUMSEC VARCHAR2(2),NOME VARCHAR2(10),CIDADE VARCHAR2(10)); 

--CRIA A TABELA EMPREGADO
CREATE TABLE EMPREGADO(NUMEMP VARCHAR2(5),NOME VARCHAR2(20),NUMSEC VARCHAR2(2),CARGO VARCHAR2(20),CHEFE VARCHAR2(20), 
SALARIO NUMBER(7,2),COMISSAO NUMBER(7,2)); 

-- CRIA A CHAVE PRIMARIA DA TABELA SECAO
ALTER TABLE SECAO ADD CONSTRAINT PK_SECAO PRIMARY KEY(NUMSEC); 

-- CRIA A CHAVE PRIMARIA DA TABELA EMPREGADO
ALTER TABLE EMPREGADO ADD CONSTRAINT PK_EMPREGADO PRIMARY KEY(NUMEMP);

-- CRIA A CHAVE ESTRANGEIRA DA TABELA SECAO NA TABELA EMPREGADO
ALTER TABLE EMPREGADO ADD CONSTRAINT FK_NUMSEC FOREIGN KEY (NUMSEC)  REFERENCES SECAO;

-- INSERE DADOS
INSERT INTO SECAO VALUES('10','SECAO1','CAMPINAS');
INSERT INTO SECAO VALUES('30','SECAO2','SAO PAULO');
INSERT INTO SECAO VALUES('60','SECAO3','FORTALEZA');
INSERT INTO SECAO VALUES('70','SECAO4','RECIFE');
INSERT INTO SECAO VALUES('90','SECAO5','MANAUS');

-- SECAO 10
INSERT INTO EMPREGADO VALUES('00010','ISRAEL','10','GERENTE','MARIO',2234.56,3000);
INSERT INTO EMPREGADO VALUES('00020','PEDRO','10','CONTABIL','ISRAEL',1815.56,400);
INSERT INTO EMPREGADO VALUES('00030','JOAO','10','VENDEDOR','ISRAEL',915.56,50);
INSERT INTO EMPREGADO VALUES('00040','PAULA','10','VENDEDOR','ISRAEL',917.56,50);
INSERT INTO EMPREGADO VALUES('00050','MARIO','10','PRESIDENTE',' ',9673.56,7000);
--SECAO 30
INSERT INTO EMPREGADO VALUES('00060','LARISSA','30','GERENTE','MARIO',2234.56,600);
INSERT INTO EMPREGADO VALUES('00070','STEPHANIE','30','CONTABIL','LARISSA',1815.56,400);
INSERT INTO EMPREGADO VALUES('00080','JULIANA','30','VENDEDOR','LARISSA',1015.56,100);
INSERT INTO EMPREGADO VALUES('00090','DANIEL','30','VENDEDOR','LARISSA',715.56,20);
INSERT INTO EMPREGADO VALUES('00100','JOANA','30','FAXINA','LARISSA',715.56,20);
--SECAO 60
INSERT INTO EMPREGADO VALUES('00110','MATHEUS','60','GERENTE','MARIO',2234.56,600);
INSERT INTO EMPREGADO VALUES('00120','PEDRO','60','CONTABIL','MATHEUS',1815.56,400);
INSERT INTO EMPREGADO VALUES('00130','FERNANDA','60','VENDEDOR','MATHEUS',1015.56,100);
INSERT INTO EMPREGADO VALUES('00140','EDUARDO','60','VENDEDOR','MATHEUS',715.56,20);
--SECAO 70
INSERT INTO EMPREGADO VALUES('00150','DIEGO','70','GERENTE','MARIO',2234.56,600);
INSERT INTO EMPREGADO VALUES('00160','VINICIUS','70','CONTABIL','DIEGO',1815.56,400);
INSERT INTO EMPREGADO VALUES('00170','BRYAN','70','VENDEDOR','DIEGO',1015.56,100);
INSERT INTO EMPREGADO VALUES('00180','MURILO','70','VENDEDOR','DIEGO',715.56,30);
--SECAO 90
INSERT INTO EMPREGADO VALUES('00190','ALESSANDRA','90','GERENTE','MARIO',2234.56,60);
INSERT INTO EMPREGADO VALUES('00200','PATRICK','90','CONTABIL','ALESSANDRA',1815.56,40);
INSERT INTO EMPREGADO VALUES('00210','WILLIAM','90','VENDEDOR','ALESSANDRA',1015.56,10);
INSERT INTO EMPREGADO VALUES('00220','BRUNO','90','VENDEDOR','ALESSANDRA',715.56,20);
INSERT INTO EMPREGADO VALUES('00230','ABIGAIL','90','MARKETING','ALESSANDRA',715.56,20);
INSERT INTO EMPREGADO VALUES('00240','FERNANDO','90','MANUTENCAO','ALESSANDRA',715.56,20);
INSERT INTO EMPREGADO VALUES('00250','MARIANA','90','FAXINA','ALESSANDRA',715.56,20);
INSERT INTO EMPREGADO VALUES('00260','BRUNA','90','ESCRITORIO','ALESSANDRA',715.56,20);



--QUESTOES

--1
SELECT NOME,CIDADE FROM SECAO WHERE NUMSEC= '70';

--2
SELECT CARGO,SALARIO,COMISSAO FROM EMPREGADO WHERE COMISSAO>SALARIO;

--3
SELECT NOME FROM SECAO WHERE CIDADE = 'CAMPINAS';

--4
SELECT DISTINCT CARGO FROM EMPREGADO ;

--5
SELECT NOME,CARGO,NUMSEC FROM EMPREGADO GROUP BY NOME,CARGO,NUMSEC HAVING NUMSEC='70' OR NUMSEC='90' OR NUMSEC='60';

--6
SELECT CARGO,SUM(SALARIO+COMISSAO) FROM EMPREGADO GROUP BY CARGO HAVING CARGO='GERENTE' OR CARGO='CONTABIL';

--7
SELECT NUMEMP,NOME,CARGO FROM EMPREGADO ORDER BY NOME ASC;

--8
SELECT NUMSEC,COUNT(NUMEMP),SUM(SALARIO+COMISSAO) FROM EMPREGADO GROUP BY NUMSEC;

--9 
SELECT NUMSEC,CARGO,COUNT(NUMEMP),AVG(SALARIO) FROM EMPREGADO GROUP BY CARGO,NUMSEC HAVING NUMSEC='70' OR NUMSEC='90' OR NUMSEC='60'; 

--10
SELECT NUMSEC,SUM(COMISSAO+SALARIO)*12,COUNT(CARGO) FROM EMPREGADO GROUP BY NUMSEC,CARGO HAVING CARGO='VENDEDOR';

--11
SELECT CARGO,AVG(SALARIO) FROM EMPREGADO GROUP BY CARGO HAVING CARGO!='PRESIDENTE';

--12
SELECT NOME,CARGO FROM EMPREGADO WHERE SALARIO+COMISSAO = (SELECT MAX(SALARIO+COMISSAO) FROM EMPREGADO);

--13  
 SELECT T.NOME,T.CARGO,T.SALARIO FROM EMPREGADO T, EMPREGADO S WHERE S.NUMSEC=10 AND T.NUMSEC != 10 AND T.SALARIO = S.SALARIO AND T.CARGO = S.CARGO;

--14 
SELECT NUMSEC,NOME,CARGO,SUM(SALARIO+COMISSAO) FROM EMPREGADO WHERE SUM(SALARIO+COMISSAO) != (SELECT MAX(SALARIO+COMISSAO) FROM EMPREGADO) AND ROWNUM=1 ORDER BY SUM(SALARIO+COMISSAO) DESC;

--15
SELECT NUMSEC,NOME,CARGO,SALARIO+COMISSAO,COMISSAO FROM EMPREGADO WHERE CARGO = 'VENDEDOR' AND NUMSEC='60' ORDER BY SALARIO DESC;

--16
SELECT NUMSEC,AVG(SALARIO) FROM EMPREGADO GROUP BY NUMSEC HAVING AVG(SALARIO)>1450;

--17
SELECT NUMSEC, COUNT(NUMSEC) FROM EMPREGADO  WHERE CARGO ='VENDEDOR' GROUP BY NUMSEC HAVING COUNT(NUMSEC)>2;

--18
SELECT NUMSEC,AVG(SALARIO) MEDIA FROM EMPREGADO GROUP BY NUMSEC HAVING AVG(SALARIO) = (SELECT MAX(MEDIA)FROM (SELECT NUMSEC,AVG(SALARIO) MEDIA FROM EMPREGADO GROUP BY NUMSEC));

--19
SELECT NOME,CARGO,SALARIO FROM EMPREGADO WHERE NUMSEC = (SELECT NUMSEC FROM EMPREGADO GROUP BY NUMSEC HAVING AVG(SALARIO) = (SELECT MAX(MEDIA)FROM (SELECT NUMSEC,AVG(SALARIO) MEDIA FROM EMPREGADO GROUP BY NUMSEC)));

--20
SELECT NOME,CARGO,SALARIO FROM EMPREGADO WHERE NUMSEC = (SELECT NUMSEC FROM SECAO WHERE CIDADE = 'CAMPINAS');

--21
SELECT NOME FROM SECAO WHERE NUMSEC IN (SELECT NUMSEC FROM EMPREGADO GROUP BY NUMSEC HAVING COUNT(*)>1);

--22
SELECT NOME FROM SECAO WHERE NUMSEC IN (SELECT NUMSEC FROM EMPREGADO GROUP BY NUMSEC HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM EMPREGADO GROUP BY NUMSEC)); 

